/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdeasRouteRouteImport } from './routes/ideas/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as IdeasNewIndexRouteImport } from './routes/ideas/new/index'
import { Route as IdeasIdeaidIndexRouteImport } from './routes/ideas/$ideaid/index'
import { Route as IdeasIdeaidEditRouteImport } from './routes/ideas/$ideaid/edit'

const IdeasRouteRoute = IdeasRouteRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewIndexRoute = IdeasNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => IdeasRouteRoute,
} as any)
const IdeasIdeaidIndexRoute = IdeasIdeaidIndexRouteImport.update({
  id: '/$ideaid/',
  path: '/$ideaid/',
  getParentRoute: () => IdeasRouteRoute,
} as any)
const IdeasIdeaidEditRoute = IdeasIdeaidEditRouteImport.update({
  id: '/$ideaid/edit',
  path: '/$ideaid/edit',
  getParentRoute: () => IdeasRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteRouteWithChildren
  '/about': typeof AboutIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid': typeof IdeasIdeaidIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid': typeof IdeasIdeaidIndexRoute
  '/ideas/new': typeof IdeasNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/ideas/$ideaid/edit': typeof IdeasIdeaidEditRoute
  '/ideas/$ideaid/': typeof IdeasIdeaidIndexRoute
  '/ideas/new/': typeof IdeasNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/about'
    | '/ideas/'
    | '/ideas/$ideaid/edit'
    | '/ideas/$ideaid'
    | '/ideas/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ideas'
    | '/ideas/$ideaid/edit'
    | '/ideas/$ideaid'
    | '/ideas/new'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/about/'
    | '/ideas/'
    | '/ideas/$ideaid/edit'
    | '/ideas/$ideaid/'
    | '/ideas/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRouteRoute: typeof IdeasRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof IdeasRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new/': {
      id: '/ideas/new/'
      path: '/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof IdeasNewIndexRouteImport
      parentRoute: typeof IdeasRouteRoute
    }
    '/ideas/$ideaid/': {
      id: '/ideas/$ideaid/'
      path: '/$ideaid'
      fullPath: '/ideas/$ideaid'
      preLoaderRoute: typeof IdeasIdeaidIndexRouteImport
      parentRoute: typeof IdeasRouteRoute
    }
    '/ideas/$ideaid/edit': {
      id: '/ideas/$ideaid/edit'
      path: '/$ideaid/edit'
      fullPath: '/ideas/$ideaid/edit'
      preLoaderRoute: typeof IdeasIdeaidEditRouteImport
      parentRoute: typeof IdeasRouteRoute
    }
  }
}

interface IdeasRouteRouteChildren {
  IdeasIndexRoute: typeof IdeasIndexRoute
  IdeasIdeaidEditRoute: typeof IdeasIdeaidEditRoute
  IdeasIdeaidIndexRoute: typeof IdeasIdeaidIndexRoute
  IdeasNewIndexRoute: typeof IdeasNewIndexRoute
}

const IdeasRouteRouteChildren: IdeasRouteRouteChildren = {
  IdeasIndexRoute: IdeasIndexRoute,
  IdeasIdeaidEditRoute: IdeasIdeaidEditRoute,
  IdeasIdeaidIndexRoute: IdeasIdeaidIndexRoute,
  IdeasNewIndexRoute: IdeasNewIndexRoute,
}

const IdeasRouteRouteWithChildren = IdeasRouteRoute._addFileChildren(
  IdeasRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRouteRoute: IdeasRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
